apiVersion: v1
kind: Service
metadata:
  name: jc-harness-quantum-bank-backend-deployment-service
  namespace: luisredda
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: ClusterIP
  ports:
    - port: 81
      targetPort: 80
      protocol: TCP
  selector:
    app: jc-harness-quantum-bank-backend-deployment
